name: Ping API on Commit

on:
  push:
    branches:
      - "**" # Trigger on any branch

jobs:
  ping-api:
    runs-on: ubuntu-latest

    steps:
      - name: Get Repository Name
        id: repo_name
        run: echo "::set-output name=name::$(basename $GITHUB_REPOSITORY)"

      - name: Ping API
        env:
          I18N_SECRET_KEY: ${{ secrets.I18N_SECRET_KEY }} # Set your secret in repository settings
          ACTIONS_ENDPOINT_URL: ${{ secrets.ACTIONS_ENDPOINT_URL }} # Set your secret in repository settings
        run: |
          curl -X GET "$ACTIONS_ENDPOINT_URL?locale=${{ steps.repo_name.outputs.name }}&secretKey=$I18N_SECRET_KEY"
