# This is a basic workflow to help you get started with Actions

name: YAML Validation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "validate-yaml"
  validate-yaml:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: YAML Lint
        uses: ibiqlik/action-yamllint@v3.0.4
        with:
          config_data: |
            extends: default
            rules:
              line-length: disable
              new-line-at-end-of-file: disable
              trailing-spaces: disable
              document-start: disable
              empty-lines: disable
              truthy: disable
